[package]
name = "seedstore-tool"
version = "1.1.1"
description = "Store a secret (such as a private key) in an encrypted file"
license = "MIT"
edition = "2021"

[dependencies]
bip39 = "2.1.0"
seedstore = { path = "../seedstore", features = ["toolhelper"] }
